WIP

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -3,6 +3,67 @@ BUILD_DIR=${1:-}
 CACHE_DIR=${2:-}
 ENV_DIR=${3:-}
 
+
+
+
+install_nodejs() {
+  local version=${1:-12.x}
+  local dir="${2:?}"
+  local code os cpu resolve_result
+
+  os=$(get_os)
+  cpu=$(get_cpu)
+
+  echo "Resolving node version $version..."
+  resolve_result=$(resolve node "$version" || echo "failed")
+
+  read -r number url < <(echo "$resolve_result")
+
+  if [[ "$resolve_result" == "failed" ]]; then
+    fail_bin_install node "$version"
+  fi
+
+  echo "Downloading and installing node $number..."
+  code=$(curl "$url" -L --silent --fail --retry 5 --retry-max-time 15 -o /tmp/node.tar.gz --write-out "%{http_code}")
+  if [ "$code" != "200" ]; then
+    echo "Unable to download node: $code" && false
+  fi
+  tar xzf /tmp/node.tar.gz -C /tmp
+  rm -rf "${dir:?}"/*
+  mv /tmp/node-v"$number"-"$os"-"$cpu"/* "$dir"
+  chmod +x "$dir"/bin/*
+}
+
+install_npm() {
+  local npm_version
+  local version="$1"
+  local dir="$2"
+  local npm_lock="$3"
+  npm_version="$(npm --version)"
+
+  # If the user has not specified a version of npm, but has an npm lockfile
+  # upgrade them to npm 5.x if a suitable version was not installed with Node
+  if $npm_lock && [ "$version" == "" ] && [ "${npm_version:0:1}" -lt "5" ]; then
+    echo "Detected package-lock.json: defaulting npm to version 5.x.x"
+    version="5.x.x"
+  fi
+
+  if [ "$version" == "" ]; then
+    echo "Using default npm version: $npm_version"
+  elif [[ "$npm_version" == "$version" ]]; then
+    echo "npm $npm_version already installed with node"
+  else
+    echo "Bootstrapping npm $version (replacing $npm_version)..."
+    if ! npm install --unsafe-perm --quiet -g "npm@$version" 2>@1>/dev/null; then
+      echo "Unable to install npm $version; does it exist?" && false
+    fi
+    echo "npm $version installed"
+  fi
+}
+
+
+
+
 # Switch to our cache directory.
 mkdir -p "$CACHE_DIR"
 cd "$CACHE_DIR"
@@ -60,3 +121,6 @@ cd $BUILD_DIR/full-app
 cargo web deploy
 mkdir -p target/deploy
 cp -r $CARGO_TARGET_DIR/deploy/* target/deploy
+
+install_nodejs
+install_npm
